IndaneApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IndaneApi.Models;
using IndaneApi.Data;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Authorization;

namespace IndaneApi.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult MyEmptyComponent()
        {
            return ViewComponent("EmptyList");
        }

        public IActionResult MyFullComponent()
        {
            return ViewComponent("FullList");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JObject AddFull([FromBody] Full full)
        {
            dynamic fulldata = new Full();
            fulldata.ProductId = full.ProductId;
            fulldata.DeliveryPersonId = full.DeliveryPersonId;
            fulldata.Out_No = full.Out_No;
            fulldata.FullCount = full.FullCount;
            fulldata.CashToBeRecevied = full.CashToBeRecevied;
            fulldata.TimeStamp = DateTime.Now.Date;
            _context.Fulls.Add(fulldata);
            _context.SaveChanges();
            return fulldata;
        }

        public IActionResult GetDelivoryBoyData()
        {
            List<DeliveryPersonDetail> dp = _context.DeliveryPersonDetails.ToList();
            return new JsonResult(dp);
        }

        public IActionResult GetProducts()
        {
            List<Product> dp = _context.Products.ToList();
            return new JsonResult(dp);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> CurrentStock()
        {
            double totalFull = 0;
            double totalEmpty = 0;
            double totalcylinder = 0;
            var load = await _context.Loadings.Include(f => f.Product).ToListAsync();

            double LoadFull = 0;
            double LoadEmpty = 0;
           // var Loadcylinder = 0;
            foreach (var item in load)
            {
                var demoFull = item.Full + LoadFull;
                var demoEmpty = item.Empty + LoadEmpty;

                LoadFull = demoFull;
                LoadEmpty = demoEmpty;

                //Loadcylinder = totalFull + totalEmpty;
            }

            var fullDelivery = await _context.Fulls.Include(f => f.DeliveryPersonDetail).Include(f => f.Product).ToListAsync();

            double delFull = 0;
            //var delEmpty = 0;
            //var delcylinder = 0;
            foreach (var full in fullDelivery)
            {
                var demoFull = full.FullCount + delFull;

                delFull = demoFull;
            }
            
            var EmptyDelivery = await _context.Empties.Include(e => e.DeliveryPersonDetail).Include(e => e.Product).ToListAsync();

            double returnFull = 0;
            double returnEmpty = 0;

            foreach (var emp in EmptyDelivery)
            {
                var demoempty = emp.EmptyNo + returnEmpty;
                var demoFull = emp.ReturnedFull + returnFull;

                returnEmpty = demoempty;
                returnFull = demoFull;
            }
            totalFull = LoadFull - delFull + returnFull;
            totalEmpty = LoadEmpty + returnEmpty;
            totalcylinder = totalEmpty + totalFull;

            ViewData["full"] = totalFull;
            ViewData["Empty"] = totalEmpty;
            ViewData["Cylinder"] = totalcylinder;

            return View();
        }

        public async Task<IActionResult> StartStock()
        {
            double totalFull = 0;
            double totalEmpty = 0;
            double totalcylinder = 0;
            var load = await _context.Loadings.Include(f => f.Product).Where(s=> s.TimeStamp.Date == DateTime.Today.AddDays(-1).Date).ToListAsync();

            double LoadFull = 0;
            double LoadEmpty = 0;
            // var Loadcylinder = 0;
            foreach (var item in load)
            {
                var demoFull = item.Full + LoadFull;
                var demoEmpty = item.Empty + LoadEmpty;

                LoadFull = demoFull;
                LoadEmpty = demoEmpty;

                //Loadcylinder = totalFull + totalEmpty;
            }

            var fullDelivery = await _context.Fulls.Include(f => f.DeliveryPersonDetail).Include(f => f.Product).Where(s => s.TimeStamp.Date == DateTime.Today.AddDays(-1).Date).ToListAsync();

            double delFull = 0;
            //var delEmpty = 0;
            //var delcylinder = 0;
            foreach (var full in fullDelivery)
            {
                var demoFull = full.FullCount + delFull;

                delFull = demoFull;
            }



            var EmptyDelivery = await _context.Empties.Include(e => e.DeliveryPersonDetail).Where(s => s.TimeStamp.Date == DateTime.Today.AddDays(-1).Date).Include(e => e.Product).ToListAsync();

            double returnFull = 0;
            double returnEmpty = 0;

            foreach (var emp in EmptyDelivery)
            {
                var demoempty = emp.EmptyNo + returnEmpty;
                var demoFull = emp.ReturnedFull + returnFull;

                returnEmpty = demoempty;
                returnFull = demoFull;
            }
            totalFull = LoadFull - delFull + returnFull;
            totalEmpty = LoadEmpty + returnEmpty;
            totalcylinder = totalEmpty + totalFull;

            ViewData["full"] = totalFull;
            ViewData["Empty"] = totalEmpty;
            ViewData["Cylinder"] = totalcylinder;

            return View();
        }

        public async Task<IActionResult> OtherproductCurrentStock()
        {
            double total = 0;
            var Load = await _context.OtherProductLoads.Include(l => l.Product).ToListAsync();

            double totalLoad = 0; 
            foreach (var item in Load)
            {
                var demo = item.ProductCount + total;

                totalLoad = demo;

            }

            var sale = await _context.OtherProductSales.Include(l => l.Product).ToListAsync();

            double totalSale = 0;
            foreach (var item in sale)
            {
                var demo = item.SaleCount + totalSale;

                totalSale = demo;
            }

            total = totalLoad - totalSale;

            ViewData["TotalLoad"] = totalLoad;
            ViewData["TotalSale"] = totalSale;
            ViewData["Total"] = total;

            return View();
        }

        public async Task<IActionResult> OtherproductstartStock()
        {
            double total = 0;
            var Load = await _context.OtherProductLoads.Include(l => l.Product).Where(s => s.TimeStamp.Date == DateTime.Today.AddDays(-1).Date).ToListAsync();

            double totalLoad = 0;
            foreach (var item in Load)
            {
                var demo = item.ProductCount + total;

                totalLoad = demo;

            }

            var sale = await _context.OtherProductSales.Include(l => l.Product).Where(s => s.TimeStamp.Date == DateTime.Today.AddDays(-1).Date).ToListAsync();

            double totalSale = 0;
            foreach (var item in sale)
            {
                var demo = item.SaleCount + totalSale;

                totalSale = demo;
            }

            total = totalLoad - totalSale;


            ViewData["TotalLoad"] = totalLoad;
            ViewData["TotalSale"] = totalSale;
            ViewData["Total"] = total;

            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IndaneApi/ViewComponents/EmptyListViewComponent.cs
using IndaneApi.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IndaneApi.ViewComponents
{
    [ViewComponent(Name = "EmptyList")]
    public class EmptyListViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        public EmptyListViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var applicationDbContext = _context.Empties.Include(e => e.DeliveryPersonDetail).Include(e => e.Product);
            foreach (var item in applicationDbContext)
            {
                item.CashToBeRecevied = (item.EmptyNo + item.NewConnection) * (item.Product.SellingPrice + item.DeliveryPersonDetail.Charges);
                item.ReceviedBalance = item.CashToBeRecevied - item.CashRecevied;
            }
            return View(await applicationDbContext.ToListAsync());
        }
    }
}

IndaneApi/ViewComponents/FullListViewComponent.cs
using IndaneApi.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IndaneApi.ViewComponents
{
    [ViewComponent(Name = "FullList")]
    public class FullListViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        public FullListViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            var items = await _context.Fulls.Include(s => s.DeliveryPersonDetail)
                                            .Include(s => s.Product)
                                            .ToListAsync();
            foreach (var item in items)
            {
                item.CashToBeRecevied = item.FullCount * (item.Product.SellingPrice + item.DeliveryPersonDetail.Charges);
            }

            return View(items);
        } 
    }
}

IndaneApi/Views/Home/CurrentStock.cshtml
@{
    ViewData["Title"] = "CurrentStock";
}

<h1>CurrentStock</h1>
<ul>
    <li>
        <p>totalFull =  @ViewData["full"]</p>
    </li>
    <li>
        <p>totalEmpty = @ViewData["Empty"]</p>
    </li>
    <li>
        <p>totalcylinder = @ViewData["Cylinder"]</p>
    </li>
</ul>

IndaneApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Full Cylinder</h3>
            <div class="form-group">
                <select id="deliveryboyid" class="form-control">
                    <option>Please Select Delivery boy</option>
                </select>
            </div>
            <div class="form-group">
                <select id="productid" class="form-control">
                    <option>Please Select Product</option>
                </select>
            </div>
            <div class="form-group">
                <input id="FullCount" placeholder="Full Count" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <select id="OutNo" class="form-control">
                    <option>Select the no of takes</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
            </div>
            @*<div class="form-group">
                <input id="Cashbal" placeholder="Cash Balance" type="number" class="form-control" />
            </div>*@
            <button type="submit" id="cylinderfull"  class="btn btn-primary btn-block">Submit</button>
        </div>
        <div class="col-md-8">
            <h3>Empty Cylinder</h3>
            <div class="form-row">
                <div class="col">
                    <select id="edeliveryboyid" class="form-control">
                        <option>Please Select Delivery boy</option>
                    </select>
                </div>
                <div class="col">
                    <select id="eproductid" class="form-control">
                        <option>Please Select Products</option>
                    </select>
                </div>
            </div>
            <br />
            <div class="form-row">
                <div class="col">
                    <select id="in_No" class="form-control">
                        <option>Select the no of In takes</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>

                <div class="col">
                    <div class="form-group">
                        <input id="emptyNo" placeholder="Sales Count" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <input id="newConnection" placeholder="New Connection" class="form-control" />
                </div>
                <div class="col">
                    <input id="emptyPending" placeholder="Empty Pending" class="form-control" />
                </div>
            </div>
            <br />

            <div class="form-row">
                <div class="col">
                    <input id="returnedFull" placeholder="Returned Full" class="form-control" />
                </div>
                <div class="col">
                    <input id="cashRecevied" placeholder="Cash Received" class="form-control" />
                </div>
            </div>
            <br />

            <div class="form-group">
                <input type="submit" id="cylinderempty" value="Submit" class="btn btn-primary btn-block" />
            </div>

        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <a href="" class="btn btn-dark" id="refreshempty">Refresh</a>
        <div class="col-md-12" id="myComponentContainer">
            @await Component.InvokeAsync("EmptyList")
        </div>

        <div class="col-md-12" id="myfullComponentContainer">
            @await Component.InvokeAsync("FullList")
        </div>
    </div>

</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            //AddData();

            $('#fulltable').DataTable();

            $('#emptytable').DataTable();

            $('#cylinderempty').click(function () {
                console.log("Entered");
                var edeliveryboy = $("#edeliveryboyid").val();
                console.log(edeliveryboy)
                var eproductId = $("#eproductid").val();
                var in_No = $("#in_No").val();
                var emptyNo = $("#emptyNo").val();
                var newConnection = $("#newConnection").val();
                var emptyPending = $("#emptyPending").val();
                var returnedFull = $("#returnedFull").val();
                var cashRecevied = $("#cashRecevied").val();


                $.ajax({
                    type: "POST",
                    url: "api/Empties",
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    data: JSON.stringify(
                        {
                            ProductId: eproductId,
                            DeliveryPersonId: edeliveryboy,
                            In_No: in_No,
                            NewConnection: newConnection,
                            EmptyNo: emptyNo,
                            EmptyPending: emptyPending,
                            ReturnedFull: returnedFull,
                            CashRecevied: cashRecevied,
                        }),
                    contentType: "appliction/json",
                    success: function (result) {
                        console.log("suceeded " + result)
                        console.log("Hello");
                        alert(result);
                        var container = $("#myComponentContainer");
                        var refreshComponent = function () {
                            console.log('hello')
                            $.get("/Home/MyEmptyComponent", function (data) { container.html(data); });
                            var data = $.get("/Home/MyEmptyComponent", function (data) { container.html(data); });
                            console.log(data);
                        };
                        refreshComponent();
                        clearDataEmpty();
                    },
                    error: function (response) {
                        alert("Please check the cash recevied or wrong entry ");
                    }
                })
            });
            $('#refreshempty').click(function () {
                var container = $("#myComponentContainer");
                var refreshComponent = function () {
                    console.log('hello')
                    $.get("/Home/MyEmptyComponent", function (data) { container.html(data); });
                    var data = $.get("/Home/MyEmptyComponent", function (data) { container.html(data); });
                    console.log(data);
                };
                refreshComponent();
            });
            function clearDataEmpty() {
                 $("#in_No").val("");
                 $("#emptyNo").val("");
                 $("#newConnection").val("");
                 $("#emptyPending").val("");
                 $("#returnedFull").val("");
                $("#cashRecevied").val("");
            }

            function clearDataFull() {
                console.log("Hello Empty boy")
                $("#FullCount").val(""); 
                $("#OutNo").val(""); 
            }

            $('#cylinderfull').click(function () {
                var deliveryboy = $("#deliveryboyid").val();
                var productId = $("#productid").val();
                var fullCount = $("#FullCount").val();
                var outNo = $("#OutNo").val();
                var cashBal = $("#Cashbal").val();

                $.ajax({
                    type: "POST",
                    url: "api/Fulls",
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    data: JSON.stringify(
                        {
                            ProductId: productId,
                            DeliveryPersonId: deliveryboy,
                            FullCount: fullCount,
                            Out_No: outNo,
                            CashToBeRecevied: cashBal
                        }),
                    contentType: "appliction/json",
                    success: function (result) {
                        //AddData();
                        alert(result);
                        var fcontainer = $("#myfullComponentContainer");
                        var fullrefreshComponent = function () {
                            $.get("/Home/MyFullComponent", function (data) { fcontainer.html(data); });
                            var data = $.get("/Home/MyFullComponent", function (data) { fcontainer.html(data); });
                        };
                        fullrefreshComponent();
                        //clearDataFull();
                         $("#deliveryboyid").val("Select");
                    },
                    error: function (result) {
                        alert("Please Enter correct values or entry exists");
                    }
                })
            });


            GetDeliveryboyData();

            function GetDeliveryboyData() {
                var options = {};
                options.url = "/Home/GetDelivoryBoyData";
                options.type = "GET";
                options.dataType = "json";
                options.success = function (data) {
                    data.forEach(function (element) {
                        console.log(element);
                        $("#deliveryboyid").append("<option value = " + element.id + ">"
                            + element.name + "</option>");
                        $("#edeliveryboyid").append("<option value = " + element.id + ">"
                            + element.name + "</option>");
                    });
                };
                options.error = function () {
                    $("#msg").html("Error while making Ajax call!");
                };
                $.ajax(options);
            }

            GetProductData();

            function GetProductData() {
                var options = {};
                options.url = "/Home/GetProducts";
                options.type = "GET";
                options.dataType = "json";
                options.success = function (data) {
                    data.forEach(function (element) {
                        console.log(element);
                        $("#productid").append("<option value = " + element.id + ">"
                            + element.name + "</option>");
                        $("#eproductid").append("<option value = " + element.id + ">"
                            + element.name + "</option>");
                    });
                };
                options.error = function () {
                    $("#msg").html("Error while making Ajax call!");
                };
                $.ajax(options);
            }
        });
    </script>
}

IndaneApi/Views/Home/OtherproductCurrentStock.cshtml
@{
    ViewData["Title"] = "OtherproductCurrentStock";
}


<h1>Current Stock</h1>  
<ul>
    <li>
        <p>totalload =  @ViewData["TotalLoad"]</p>
    </li>
    <li>
        <p>totalsales = @ViewData["TotalSale"]</p>
    </li>
    <li>
        <p>total = @ViewData["Total"]</p>
    </li>
</ul>

IndaneApi/Views/Home/OtherproductstartStock.cshtml
@{
    ViewData["Title"] = "OtherproductstartStock";
}

<h1>Opening Stock</h1>
<ul>
    <li>
        <p>totalload =  @ViewData["TotalLoad"]</p>
    </li>
    <li>
        <p>totalsale = @ViewData["TotalSale"]</p>
    </li>
    <li>
        <p>total = @ViewData["Total"]</p>
    </li>
</ul>

IndaneApi/Views/Home/StartStock.cshtml
@{
    ViewData["Title"] = "StartStock";
}

<h1>Opening Stock</h1>
<ul>
    <li>
        <p>totalFull =  @ViewData["full"]</p>
    </li>
    <li>
        <p>totalEmpty = @ViewData["Empty"]</p>
    </li>
    <li>
        <p>totalcylinder = @ViewData["Cylinder"]</p>
    </li>
</ul>