IndaneApi/Controllers/FullsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndaneApi.Data;
using IndaneApi.Models;

namespace IndaneApi.Controllers
{
    public class FullsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FullsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Fulls
        public async Task<IActionResult> Index()
        {
            var applicationDbContext =await _context.Fulls.Include(f => f.DeliveryPersonDetail).Include(f => f.Product).ToListAsync();

            foreach (var item in applicationDbContext)
            {
                item.CashToBeRecevied = item.FullCount * (item.Product.SellingPrice + item.DeliveryPersonDetail.Charges);
            }
            return View(applicationDbContext);
        }

        // GET: Fulls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var full = await _context.Fulls
                .Include(f => f.DeliveryPersonDetail)
                .Include(f => f.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (full == null)
            {
                return NotFound();
            }

            return View(full);
        }

        // GET: Fulls/Create
        public IActionResult Create()
        {
            ViewData["DeliveryPersonId"] = new SelectList(_context.DeliveryPersonDetails, "Id", "Name");
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }

        // POST: Fulls/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,DeliveryPersonId,FullCount,TimeStamp,Out_No")] Full full)
        {
            if (ModelState.IsValid)
            {
                full.TimeStamp = DateTime.Now;
                _context.Add(full);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeliveryPersonId"] = new SelectList(_context.DeliveryPersonDetails, "Id", "Id", full.DeliveryPersonId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", full.ProductId);
            return View(full);
        }

        // GET: Fulls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var full = await _context.Fulls.FindAsync(id);
            if (full == null)
            {
                return NotFound();
            }
            ViewData["DeliveryPersonId"] = new SelectList(_context.DeliveryPersonDetails, "Id", "Id", full.DeliveryPersonId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", full.ProductId);
            return View(full);
        }

        // POST: Fulls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,DeliveryPersonId,FullCount,TimeStamp,Out_No")] Full full)
        {
            if (id != full.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(full);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FullExists(full.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeliveryPersonId"] = new SelectList(_context.DeliveryPersonDetails, "Id", "Id", full.DeliveryPersonId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", full.ProductId);
            return View(full);
        }

        // GET: Fulls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var full = await _context.Fulls
                .Include(f => f.DeliveryPersonDetail)
                .Include(f => f.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (full == null)
            {
                return NotFound();
            }

            return View(full);
        }

        // POST: Fulls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var full = await _context.Fulls.FindAsync(id);
            _context.Fulls.Remove(full);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FullExists(int id)
        {
            return _context.Fulls.Any(e => e.Id == id);
        }
    }
}

IndaneApi/Controllers/LoadingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndaneApi.Data;
using IndaneApi.Models;

namespace IndaneApi.Controllers
{
    public class LoadingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoadingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Loadings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = await _context.Loadings.Include(l => l.Product).ToListAsync();
            foreach (var item in applicationDbContext)
            {
                if (item.LoadType == "2way")
                {
                    
                    item.Empty = item.Full;
                   
                }
                else
                {
                   
                    item.Empty = 0;
                    
                }
            }
            return View( applicationDbContext);
        }

        // GET: Loadings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loading = await _context.Loadings
                .Include(l => l.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loading == null)
            {
                return NotFound();
            }

            return View(loading);
        }

        // GET: Loadings/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }

        // POST: Loadings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,LoadType,TimeStamp,LoadCount,Full")] Loading loading)
        {
            if (ModelState.IsValid)
            {
                loading.TimeStamp = DateTime.Now;
                _context.Add(loading);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", loading.ProductId);
            return View(loading);
        }

        // GET: Loadings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loading = await _context.Loadings.FindAsync(id);
            if (loading == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", loading.ProductId);
            return View(loading);
        }

        // POST: Loadings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,LoadType,TimeStamp,LoadCount,Full")] Loading loading)
        {
            if (id != loading.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loading);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoadingExists(loading.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", loading.ProductId);
            return View(loading);
        }

        // GET: Loadings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loading = await _context.Loadings
                .Include(l => l.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loading == null)
            {
                return NotFound();
            }

            return View(loading);
        }

        // POST: Loadings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loading = await _context.Loadings.FindAsync(id);
            _context.Loadings.Remove(loading);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoadingExists(int id)
        {
            return _context.Loadings.Any(e => e.Id == id);
        }


        //Customized Action
        public async Task<IActionResult> LoadReport()
        {
            var applicationDbContext = await _context.Loadings.Include(l => l.Product).ToListAsync();
            foreach (var item in applicationDbContext)
            {
                if (item.LoadType == "2way")
                {

                    item.Empty = item.Full;

                }
                else
                {

                    item.Empty = 0;

                }

                item.Expense = item.Full * item.Product.CostPrice;
            }
            return View(applicationDbContext);
        }
    }
}

IndaneApi/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndaneApi.Data;
using IndaneApi.Models;

namespace IndaneApi.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,CostPrice,SellingPrice,Weight,TimeStamp")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.TimeStamp = DateTime.Now;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CostPrice,SellingPrice,Weight,TimeStamp")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

IndaneApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IndaneApi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Senthur Azhagar Gas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Dashboard <span class="sr-only">(current)</span></a>
                </li>
                @if (!User.IsInRole("Staff"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="DeliveryPersonDetails">Delivery Guys</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Products">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Loadings">Loadings</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reports
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-action="Index" asp-controller="Fulls">Full Cylinders</a>
                            <a class="dropdown-item" asp-action="Index" asp-controller="Empties">Cyclinder for Refills</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-action="CurrentStock" asp-controller="Home">Cylinder Current Stock Report</a>
                            <a class="dropdown-item" asp-action="StartStock" asp-controller="Home">Cylinder Opening Stock Report</a>
                            <a class="dropdown-item" asp-action="OtherProductCurrentStock" asp-controller="Home">Other Products Current Stock Report</a>
                            <a class="dropdown-item" asp-action="OtherProductStartStock" asp-controller="Home">Other Products Opening Stock Report</a>
                            <a class="dropdown-item" asp-action="Cylinder1" asp-controller="Empties">14Kg Cylinder Report</a>
                            <a class="dropdown-item" asp-action="Cylinder2" asp-controller="Empties">19Kg Cylinder Report</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="OtherProductLoads">Other Product Loads</a>
                    </li>

                }
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="OtherProductSales">Other Products Sales</a>
                </li>

                <li class="nav-item">
                    <partial name="_LoginPartial" />
                </li>
            </ul>
        </div>
    </nav>
    @*<nav class="navbar navbar-dark sticky-top bg-primary flex-md-nowrap p-0">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
                Senthur Azhagar Gas  | @User.Identity.Name
            </a>
            <input class="form-control form-control-light w-100" type="text" placeholder="Search" aria-label="Search">
            <ul class="navbar-nav px-3">
            </ul>
        </nav>*@
    @*<div class="container-fluid">
            <div class="row">

                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" href="/">
                                    <span data-feather="home"></span>
                                    Dashboard <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="DeliveryPersonDetails">
                                    <span data-feather="file"></span>
                                    Delivery Guys
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Products">
                                    <span data-feather="shopping-cart"></span>
                                    Products
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Loadings">
                                    <span data-feather="users"></span>
                                    Loads
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="OtherProductLoads">
                                    <span data-feather="bar-chart-2"></span>
                                    Other Product Loads
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="OtherProductSales">
                                    <span data-feather="layers"></span>
                                    Other Product Sales
                                </a>
                            </li>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Reports</span>
                            <a class="d-flex align-items-center text-muted" href="#">
                                <span data-feather="plus-circle"></span>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-2">
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Fulls">
                                    <span data-feather="file-text"></span>
                                    Full Cylinders
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Empties">
                                    <span data-feather="file-text"></span>
                                    Cylinders for Refill
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="CurrentStock" asp-controller="Home">
                                    <span data-feather="file-text"></span>
                                    Cylinder Current Stock Report
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="StartStock" asp-controller="Home">
                                    <span data-feather="file-text"></span>
                                    Cylinder Opening Stock Report
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="OtherProductCurrentStock" asp-controller="Home">
                                    <span data-feather="file-text"></span>
                                    Product Current Stock Report
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="OtherProductStartStock" asp-controller="Home">
                                    <span data-feather="file-text"></span>
                                    Product Opening Stock Report
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>*@
    <main role="main" class="container col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        @RenderBody()
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - IndaneApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </main>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>